const MATKUL_DATA = [
  {
    id: '1',
    kode: 'IF101',
    nama: 'Algoritma dan Pemrograman',
    dosen: 'Dr. Andi Wijaya, M.Kom',
    sks: 3,
    semester: 2,
    deskripsi:
      'Mata kuliah ini membahas konsep dasar algoritma, flowchart, pseudocode, serta implementasi menggunakan bahasa pemrograman. Mahasiswa akan mempelajari struktur data dasar, kontrol alur program, dan teknik pemecahan masalah secara sistematis.',
    jadwal: 'Senin, 08:00 - 10:30 WIB',
    ruang: 'Lab Komputer 2',
    materi: [
      { id: 'm1', judul: 'Pengenalan Algoritma', selesai: false },
      { id: 'm2', judul: 'Flowchart dan Pseudocode', selesai: false },
      { id: 'm3', judul: 'Variabel dan Tipe Data', selesai: false },
      { id: 'm4', judul: 'Percabangan (If-Else)', selesai: false },
      { id: 'm5', judul: 'Perulangan (Loop)', selesai: false },
      { id: 'm6', judul: 'Array dan String', selesai: false },
      { id: 'm7', judul: 'Fungsi dan Prosedur', selesai: false },
      { id: 'm8', judul: 'Sorting dan Searching', selesai: false },
    ],
  },
  {
    id: '2',
    kode: 'IF202',
    nama: 'Basis Data',
    dosen: 'Prof. Budi Santoso, Ph.D',
    sks: 3,
    semester: 3,
    deskripsi:
      'Mempelajari perancangan dan implementasi basis data relasional. Topik meliputi model ER, normalisasi, SQL, serta pengelolaan transaksi dan keamanan database.',
    jadwal: 'Selasa, 10:00 - 12:30 WIB',
    ruang: 'Lab Komputer 1',
    materi: [
      { id: 'm1', judul: 'Konsep Basis Data', selesai: false },
      { id: 'm2', judul: 'Model Entity-Relationship', selesai: false },
      { id: 'm3', judul: 'Normalisasi', selesai: false },
      { id: 'm4', judul: 'SQL Dasar (DDL & DML)', selesai: false },
      { id: 'm5', judul: 'SQL Lanjutan (JOIN & Subquery)', selesai: false },
      { id: 'm6', judul: 'Indexing dan Optimasi', selesai: false },
      { id: 'm7', judul: 'Transaksi dan Concurrency', selesai: false },
    ],
  },
  {
    id: '3',
    kode: 'IF303',
    nama: 'Pemrograman Web',
    dosen: 'Siti Rahayu, S.Kom, M.Cs',
    sks: 3,
    semester: 4,
    deskripsi:
      'Mata kuliah ini membahas pengembangan aplikasi web dari sisi frontend dan backend. Mahasiswa akan belajar HTML, CSS, JavaScript, serta framework modern untuk membangun web interaktif.',
    jadwal: 'Rabu, 13:00 - 15:30 WIB',
    ruang: 'Lab Komputer 3',
    materi: [
      { id: 'm1', judul: 'HTML5 Semantik', selesai: false },
      { id: 'm2', judul: 'CSS3 dan Responsive Design', selesai: false },
      { id: 'm3', judul: 'JavaScript Dasar', selesai: false },
      { id: 'm4', judul: 'DOM Manipulation', selesai: false },
      { id: 'm5', judul: 'Fetch API dan AJAX', selesai: false },
      { id: 'm6', judul: 'Node.js dan Express', selesai: false },
      { id: 'm7', judul: 'REST API Development', selesai: false },
      { id: 'm8', judul: 'Deployment', selesai: false },
    ],
  },
  {
    id: '4',
    kode: 'IF404',
    nama: 'Jaringan Komputer',
    dosen: 'Ir. Cahyo Purnomo, M.T',
    sks: 3,
    semester: 4,
    deskripsi:
      'Membahas arsitektur jaringan komputer, model OSI/TCP-IP, protokol komunikasi, subnetting, routing, serta keamanan jaringan dasar.',
    jadwal: 'Kamis, 08:00 - 10:30 WIB',
    ruang: 'Ruang 401',
    materi: [
      { id: 'm1', judul: 'Pengenalan Jaringan', selesai: false },
      { id: 'm2', judul: 'Model OSI dan TCP/IP', selesai: false },
      { id: 'm3', judul: 'IP Addressing dan Subnetting', selesai: false },
      { id: 'm4', judul: 'Routing dan Switching', selesai: false },
      { id: 'm5', judul: 'Transport Layer (TCP/UDP)', selesai: false },
      { id: 'm6', judul: 'Application Layer Protocols', selesai: false },
      { id: 'm7', judul: 'Keamanan Jaringan Dasar', selesai: false },
    ],
  },
  {
    id: '5',
    kode: 'IF505',
    nama: 'Pemrograman Mobile',
    dosen: 'Dewi Lestari, S.Kom, M.Kom',
    sks: 3,
    semester: 5,
    deskripsi:
      'Mata kuliah ini membahas pengembangan aplikasi mobile menggunakan React Native dan Expo. Mahasiswa akan membangun aplikasi cross-platform yang berjalan di Android dan iOS.',
    jadwal: 'Jumat, 10:00 - 12:30 WIB',
    ruang: 'Lab Komputer 2',
    materi: [
      { id: 'm1', judul: 'Pengenalan React Native', selesai: false },
      { id: 'm2', judul: 'Komponen dan Props', selesai: false },
      { id: 'm3', judul: 'State dan Lifecycle', selesai: false },
      { id: 'm4', judul: 'Navigation (Stack & Tab)', selesai: false },
      { id: 'm5', judul: 'FlatList dan ScrollView', selesai: false },
      { id: 'm6', judul: 'AsyncStorage', selesai: false },
      { id: 'm7', judul: 'Device Features (Kamera, Lokasi)', selesai: false },
      { id: 'm8', judul: 'Build dan Deploy (EAS)', selesai: false },
    ],
  },
  {
    id: '6',
    kode: 'IF606',
    nama: 'Kecerdasan Buatan',
    dosen: 'Dr. Fajar Hidayat, M.Sc',
    sks: 3,
    semester: 6,
    deskripsi:
      'Mempelajari konsep dasar AI meliputi search algorithms, knowledge representation, machine learning dasar, neural networks, dan natural language processing.',
    jadwal: 'Senin, 13:00 - 15:30 WIB',
    ruang: 'Ruang 302',
    materi: [
      { id: 'm1', judul: 'Pengenalan AI', selesai: false },
      { id: 'm2', judul: 'Search Algorithms', selesai: false },
      { id: 'm3', judul: 'Knowledge Representation', selesai: false },
      { id: 'm4', judul: 'Machine Learning Dasar', selesai: false },
      { id: 'm5', judul: 'Neural Networks', selesai: false },
      { id: 'm6', judul: 'Natural Language Processing', selesai: false },
    ],
  },
];

export default MATKUL_DATA;
